services: 
  - type: web
    name: bluecall
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn monprojet.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: monprojet.settings
      - key: PYTHON_VERSION
        value: 3.11
