# Generated by Django 5.2 on 2025-07-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0002_alter_category_image_file_alter_product_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='command',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
