# Generated by Django 5.2 on 2025-04-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0002_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='total',
            field=models.CharField(default='500', max_length=200),
            preserve_default=False,
        ),
    ]
