# Generated by Django 5.2 on 2025-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0003_command_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
