# Generated by Django 5.2 on 2025-04-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0004_product_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
