# Generated by Django 5.2 on 2025-07-04 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0004_product_image_alter_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panieritem',
            unique_together={('user', 'produit')},
        ),
    ]
