# Generated by Django 5.2 on 2025-04-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0005_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
