# Generated by Django 5.2 on 2025-04-27 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0007_command_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green.command')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green.product')),
            ],
        ),
    ]
