# Generated by Django 5.2 on 2025-04-27 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0008_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='date_command',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
