# Generated by Django 5.2 on 2025-04-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0009_alter_command_date_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='statut',
            field=models.CharField(default='livraison en cours', max_length=100),
        ),
    ]
