# Generated by Django 5.2 on 2025-04-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0010_command_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='taille',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
