# Generated by Django 5.2 on 2025-04-27 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0011_command_taille'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='date_command',
            new_name='date_commande',
        ),
    ]
