# Generated by Django 5.2 on 2025-04-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0012_rename_date_command_command_date_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='date_commande',
            new_name='date_command',
        ),
    ]
