# Generated by Django 5.2 on 2025-04-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0013_rename_date_commande_command_date_command'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_nom',
        ),
    ]
